version: '2'
services:
  postgres:
    image: blockchainbox/postgres:latest
    build: postgres/
    ports:
      - 5432:5432
  kafka:
    image: blockchainbox/kafka:latest
    build: kafka/
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"  
  blockchainbox:
    image: blockchainbox/blockchainbox:latest
    build: blockchainbox/
    links:
      - kafka:kafka
      - postgres:postgres
    ports:
      - 8080:8080
      