version: '2'
services:
  postgres:
    image: blockchainbox/postgres:latest
    build: postgres/
    ports:
      - 5432:5432
  kafka:
    image: blockchainbox/kafka:latest
    build: kafka/
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "InsertQueue:1:3,ReadQueue:1:3"
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"  
  ethereum:
    image: blockchainbox/ethereum:latest
    build: ethereum/   
    ports:
      - 3000:3000
      - 8545:8545
      - 30303:30303
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - postgres:postgres
