version: '2'
services:
  postgres:
    image: blockchainbox/postgres:latest
    build: postgres/
    ports:
      - 5432:5432
  kafka:
    image: blockchainbox/kafka:latest
    build: kafka/
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "InsertQueue:1:1,ReadQueue:1:1,InsertCheckMinedQueue:1:1,ReadCheckMinedQueue:1:1,ContractQueue:1:1"
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"  
